data:
    type: "LLdataset"
    train_dataset: "puwell"
    val_dataset: "puwell"
    patch_size: 256
    channels: 3
    num_workers: 4
    # data_dir: "/kaggle/input/cyclegan-synthetic-data/pytorch-CycleGAN-and-pix2pix/results/puwell/test_latest/images/"
    # data_dir: "/kaggle/input/puwell-test/Puwell_Test/"
    data_dir: "/kaggle/input/create-dataset-for-test/"
    ckpt_dir: "ckpt/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200

training:
    batch_size: 8
    n_epochs: 30
    validation_freq: 800

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00005
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8
